version: '2'
services:
  mysql:
    container_name: gameaholic_mysql
    ports:
    - "3306:3306"
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root' # TODO: Change this
      MYSQL_USER: 'gameaholic'
      MYSQL_PASS: 'gameaholic'
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:
